---
title: "Confidence and accuracy across baseline"
author: "Yosuke Sakamoto"
date: "2023-06-12"
output: pdf_document
---
# Import library
```{r warning = FALSE, message = FALSE}
library(tidyverse)
library(lme4)
library(lmerTest)
library(car)
library(cowplot)
library(ggbreak)
library(ggeffects)
```

# Import data 
```{r}
df <- read.csv("data_behavior.csv", header = TRUE)
df$LogDiff <- scale(df$LogDiff)
df$LogTot <- scale(df$LogTot)
df$LogDCE <- scale(df$LogDCE)
df$LogDICE <- scale(df$LogDICE)
df$Conf <- scale(df$Conf)
df <- mutate(df, DiffRL = RVal - LVal, LogDiffRL = LogRVal - LogLVal)
df_more <- filter(df, BlockCond == "MORE")
df_less <- filter(df, BlockCond == "LESS")
df %>% 
  mutate(Baseline = if_else(LVal == 50 | RVal == 50, 1, if_else(LVal == 100 | RVal == 100, 2, 3))) -> df
df$Baseline <- as.factor(df$Baseline)
```

# Accuracy
```{r}
a1 <- glmer(Corr ~ Baseline * LogDiff + BlockCond + Baseline:BlockCond + LogDiff:BlockCond + (1|id), 
            data = df, family = binomial, control = glmerControl(optimizer = "nlminbwrap"))
summary(a1)
Anova(a1)
plot(ggpredict(a1, terms = c("Baseline", "LogDiff", "BlockCond")))
 
a2 <- glmer(Corr ~ LogTot * LogDiff + BlockCond + LogTot:BlockCond + LogDiff:BlockCond + (1|id), 
            data = df, family = binomial, control = glmerControl(optimizer = "nlminbwrap"))
summary(a2)
Anova(a2)
plot(ggpredict(a2, terms = c("LogTot", "LogDiff", "BlockCond"))) 
```

# Confidence
```{r}
c1 <- lmer(Conf ~ LogDCE * LogDICE + BlockCond + LogDCE:BlockCond + LogDICE:BlockCond + (1|id), data = df, 
           REML = F, control = lmerControl(optimizer = "nlminbwrap"))
summary(c1)
Anova(c1)
plot(ggpredict(c1, terms = c("LogDCE", "LogDICE", "BlockCond"))) 
 
c2 <- lmer(Conf ~ LogTot * LogDiff + BlockCond + LogTot:BlockCond + LogDiff:BlockCond + (1|id), 
           data = df, REML = F, control = lmerControl(optimizer = "nlminbwrap"))
summary(c2)
Anova(c2)
plot(ggpredict(c2, terms = c("LogTot", "LogDiff", "BlockCond"))) 

```

## Include baseline (as.factor)
```{r}
b1 <- lmer(Conf ~ LogDCE * LogDICE + BlockCond + BlockCond:LogDCE + BlockCond:LogDICE + Baseline + Baseline:BlockCond + (1|id), data = df, 
          REML = F, control = lmerControl(optimizer = "nlminbwrap"))
summary(b1)
Anova(b1)
plot(ggpredict(b1, terms = c("LogDCE", "LogDICE", "Baseline", "BlockCond")))
plot(ggpredict(b1, terms = c("Baseline", "BlockCond")))
```